version: v1.0
name: ''
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
apiVersion: v1alpha
kind: Secret
metadata:
  name: gcr-secret
data:
  env_vars:
    - name: GCP_PROJECT_ID
      value: your-gcp-project-id
    - name: GCP_PROJECT_DEFAULT_ZONE
      value: europe-west1-b
  files:
    - path: .secrets.gcp.json
      content: PASTE_BASE64_ENCODED_CONTENT_HERE
blocks: []
